/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-11-30 18:49:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import travel.DAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("travel.DAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.title-bar{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tfont-family: serif;\r\n");
      out.write("\tfont-size: 100px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #1abc9c;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.error{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 30px;\r\n");
      out.write("\t\tfont-family: serif;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.travel-form{\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\talign-content: center;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tbackground-color: #DBDADA;\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.travel-form form{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.travel-form select, input{\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\twidth: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.search{\r\n");
      out.write("\t\tbackground-color: #000faa;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tfont-style: strong;\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\tfont-weight: 300;\r\n");
      out.write("\t\tfont-family: monospace;\r\n");
      out.write("\t\tborder-radius: 100px;\r\n");
      out.write("\t\tborder: solid;\r\n");
      out.write("\t\tbackground-image: linear-gradient(to bottom right, #6666ff, #9999ff, #0066ff); \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.special-deals{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\tfont-family: serif;\r\n");
      out.write("\t\tfont-size: 50px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tfont-family: cursive;\r\n");
      out.write("\t\tbackground-image: linear-gradient(to bottom right, #0636ff, #0699ff, #f016ff);  \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.offer{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tbackground-color: #1abc9c;\r\n");
      out.write("\t\tbackground-image: radial-gradient(red, yellow);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.normal-text{\r\n");
      out.write("\t\tfont-size: 25px;\r\n");
      out.write("\t\tfont-family: serif;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.discount{\r\n");
      out.write("\t\tfont-size: 70px;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.source{\r\n");
      out.write("\t\tfont-size: 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Hide the images by default */\r\n");
      out.write("\t.slide {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Next & previous buttons */\r\n");
      out.write("\t.prev, .next {\r\n");
      out.write("\t  cursor: pointer;\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 50%;\r\n");
      out.write("\t  width: auto;\r\n");
      out.write("\t  margin-top: -75px;\r\n");
      out.write("\t  padding: 16px;\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  font-weight: bold;\r\n");
      out.write("\t  font-size: 18px;\r\n");
      out.write("\t  transition: 0.6s ease;\r\n");
      out.write("\t  border-radius: 0 3px 3px 0;\r\n");
      out.write("\t  user-select: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Position the \"next button\" to the right */\r\n");
      out.write("\t.next {\r\n");
      out.write("\t  right: 0;\r\n");
      out.write("\t  border-radius: 3px 0 0 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* On hover, add a black background color with a little bit see-through */\r\n");
      out.write("\t.prev:hover, .next:hover {\r\n");
      out.write("\t  background-color: rgba(0,0,0,0.8);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction timeDiff(target) {\r\n");
      out.write("\t\tfunction z(n) {return (n<10? '0' : '') + n;}\r\n");
      out.write("\t\tvar timeDiff = target - (new Date()); \r\n");
      out.write("\t\tvar hours    = timeDiff / 3.6e6 | 0;\r\n");
      out.write("\t\tvar minutes  = timeDiff % 3.6e6 / 6e4 | 0;\r\n");
      out.write("\t\tvar seconds  = timeDiff % 6e4 / 1e3 | 0;\r\n");
      out.write("\t\tif (hours<0 || minutes<0 || seconds<0) {\r\n");
      out.write("\t\t  document.getElementById('divBody').style.display='none';\r\n");
      out.write("\t\t  document.getElementById('divExpired').style.display='';    \r\n");
      out.write("\t\t  return '<b>EXPIRED</b>';\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t  return '<b>' + z(hours) + '</b> h <b>' + z(minutes) + '</b>  m <b>' + z(seconds) + '</b> s';\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\tvar addFunctionOnWindowLoad = function(callback){\r\n");
      out.write("\t  if(window.addEventListener){\r\n");
      out.write("\t\t  window.addEventListener('load',callback,false);\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t\t  window.attachEvent('onload',callback);\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Title bar -->\r\n");
      out.write("<div class=\"title-bar\">\r\n");
      out.write("\t<h1> TravelThruAir </h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String url,user,pass;
	url="jdbc:mysql://localhost:3306/travel";
	System.out.println(url);
	user="root";
	pass="";
	
	DAO dao=new DAO(url,user,pass);
	ResultSet rs;
	rs=dao.getCities();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Form -->\r\n");
      out.write("<div class=\"travel-form\">\r\n");
      out.write("\t<form action=\"search\" id=\"travel-form\" method=\"post\">\r\n");
      out.write("\t\t<select class=\"src\" id=\"src\" name=\"src\">\r\n");
      out.write("\t\t\t");

				do
				{
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(rs.getString("code"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("code"));
      out.write('-');
      out.print(rs.getString("city"));
      out.write(" </option>\r\n");
      out.write("\t\t\t\t");
}
				while(rs.next());
				rs=dao.getCities();
			
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t<select class=\"dest\" id=\"dest\" name=\"dest\">\r\n");
      out.write("\t\t\t");

				do
				{
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(rs.getString("code"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("code"));
      out.write('-');
      out.print(rs.getString("city"));
      out.write(" </option>\r\n");
      out.write("\t\t\t\t");
}
				while(rs.next());
			
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"date\" id=\"date\" name=\"date\" required=\"\">\r\n");
      out.write("\t\t<input class=\"search\" type=\"button\" value=\"SEARCH\" onclick=\"validate_and_submit()\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"special-deals\">\r\n");
      out.write("\tSPECIAL DEALS\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Offers -->\r\n");
      out.write("<div class=\"offers-container\">\r\n");
      out.write("\t");

		rs=dao.getOffers();
		if(rs==null)
		{
      out.write("\r\n");
      out.write("\t\t\t<div class=\"error\">No offers right now</div>\r\n");
      out.write("\t\t");
 }
		else
		{
			do
			{
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"offer slide\">\r\n");
      out.write("\t\t\t\t\t<!-- START TIME: ");
      out.print(rs.getString("start_time") );
      out.write("\r\n");
      out.write("\t\t\t\t\tEND TIME: ");
      out.print(rs.getString("end_time") );
      out.write(" -->\r\n");
      out.write("\t\t\t\t\t<div class=\"normal-text\">Flat</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"discount\"><strong>");
      out.print(rs.getString("discount") );
      out.write("%</strong> off</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"normal-text\">on flights</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"source\"><strong>");
      out.print(rs.getString("src") );
      out.write(" </strong> <span style='font-size:75px;'>&#8594;</span> <strong>");
      out.print(rs.getString("dest") );
      out.write(" </strong></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"normal-text\"><div id=\"countdown");
      out.print(rs.getString("id"));
      out.write("\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javaScript\">              \r\n");
      out.write("\t\t\t\t\t\t  function doCountDown");
      out.print(rs.getString("id"));
      out.write("(target) {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('countdown");
      out.print(rs.getString("id"));
      out.write("').innerHTML = '<span style=\\\"color:white\\\"><b>EXPIRES IN</b></span>: ' + timeDiff(target);\r\n");
      out.write("\t\t\t\t\t\t\tvar lag = 1020 - (new Date() % 100);\r\n");
      out.write("\t\t\t\t\t\t\tsetTimeout(function(){doCountDown");
      out.print(rs.getString("id"));
      out.write("(target);}, lag);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t  var x");
      out.print(rs.getString("id"));
      out.write(" = function doStart");
      out.print(rs.getString("id"));
      out.write("() {\r\n");
      out.write("\t\t\t\t\t\t\t//Insert Expiration Date from mySQL into t var\r\n");
      out.write("\t\t\t\t\t\t\tvar t=\"");
      out.print(rs.getString("end_time"));
      out.write("\".split(/[- :]/);\r\n");
      out.write("\t\t\t\t\t\t\tdoCountDown");
      out.print(rs.getString("id"));
      out.write("(new Date(t[0],t[1]-1,t[2],t[3],t[4],t[5]));\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  addFunctionOnWindowLoad(x");
      out.print(rs.getString("id"));
      out.write(");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</script> \r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Next and previous buttons -->\r\n");
      out.write("\t\t\t\t<a class=\"prev\" onclick=\"plusSlides(-1)\">&#10094;</a>\r\n");
      out.write("\t\t\t\t<a class=\"next\" onclick=\"plusSlides(1)\">&#10095;</a>\r\n");
      out.write("\t\t\t");
}
			while(rs.next());
		}
	
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar today = new Date().toISOString().split('T')[0];\r\n");
      out.write("\tdocument.getElementsByName(\"date\")[0].setAttribute('min', today);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//Script for slideshow\r\n");
      out.write("\tvar slideIndex = 1;\r\n");
      out.write("\tshowSlides(slideIndex);\r\n");
      out.write("\tshowSlidesAuto();\r\n");
      out.write("\r\n");
      out.write("\t// Next/previous controls\r\n");
      out.write("\tfunction plusSlides(n) {\r\n");
      out.write("\t  showSlides(slideIndex += n);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// Thumbnail image controls\r\n");
      out.write("\tfunction currentSlide(n) {\r\n");
      out.write("\t  showSlides(slideIndex = n);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction showSlides(n) {\r\n");
      out.write("\t  var i;\r\n");
      out.write("\t  var slides = document.getElementsByClassName(\"slide\");\r\n");
      out.write("\t  console.log(slides.length);\r\n");
      out.write("\t  if (n > slides.length) {slideIndex = 1}\r\n");
      out.write("\t  if (n < 1) {slideIndex = slides.length}\r\n");
      out.write("\t  for (i = 0; i < slides.length; i++) {\r\n");
      out.write("\t\t  slides[i].style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t  slides[slideIndex-1].style.display = \"block\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction showSlidesAuto() {\r\n");
      out.write("\t  var i;\r\n");
      out.write("\t  var slides = document.getElementsByClassName(\"slide\");\r\n");
      out.write("\t  for (i = 0; i < slides.length; i++) {\r\n");
      out.write("\t    slides[i].style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t  slideIndex++;\r\n");
      out.write("\t  if (slideIndex > slides.length) {slideIndex = 1}\r\n");
      out.write("\t  slides[slideIndex-1].style.display = \"block\";\r\n");
      out.write("\t  setTimeout(showSlidesAuto, 5000); // Change image every 2 seconds\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction validate_and_submit(){\r\n");
      out.write("\t\tvar src=document.getElementById(\"src\").value;\r\n");
      out.write("\t\tvar dest=document.getElementById(\"dest\").value;\r\n");
      out.write("\t\tif(src===dest)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//Error\r\n");
      out.write("\t\t\talert(\"Source and destination city cannot be same\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tdocument.getElementById(\"travel-form\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
