CREATE TABLE DEPARTMENT320 (DEPT_CODE CHAR(5) PRIMARY KEY, DEPT_NAME CHAR(20));
CREATE TABLE EMP320 (EMP_CODE CHAR(5) PRIMARY KEY, EMP_NAME CHAR(20), DEPT_CODE CHAR(5) REFERENCES DEPARTMENT320(DEPT_CODE), ADDRESS CHAR(50), CITY CHAR(10), BASIC NUMBER CHECK (BASIC>=5000 AND BASIC<=9000), DT_JOIN DATE);
CREATE TABLE LEAVE20 (EMP_CODE CHAR(5) REFERENCES EMP320(EMP_CODE), LTYPE CHAR(5), FRM_DT DATE, TO_DT DATE);
ALTER TABLE EMP320 MODIFY (DT_JOIN DATE DEFAULT SYSDATE NOT NULL);


