/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-09-15 17:13:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import com.shopping.DAO;
import com.shopping.User;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.shopping.User");
    _jspx_imports_classes.add("com.shopping.DAO");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<mvc:resources location=\"images/\" mapping=\"images/**\"></mvc:resources>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tul {\r\n");
      out.write("\t\tlist-style-type: none;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 2px;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\tbackground-color: #333;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tli {\r\n");
      out.write("\t\tpadding:1px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tcolor: #ffffff;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.cards{\r\n");
      out.write("\t\twidth:10%;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tborder-radius: 10px;\r\n");
      out.write("\t\tmargin:40px;\r\n");
      out.write("\t\tbox-shadow:2px 2px 10px black;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.image img{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.title{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.price{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tpadding:4px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.origPrice{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 16px;\r\n");
      out.write("\t\tpadding:4px;\r\n");
      out.write("\t\ttext-decoration: line-through;\r\n");
      out.write("\t\tcolor: grey;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.nameDisp{\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.logout a{\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.ribbon {\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  left: -5px; top: -5px;\r\n");
      out.write("\t  z-index: 1;\r\n");
      out.write("\t  overflow: hidden;\r\n");
      out.write("\t  width: 75px; height: 75px;\r\n");
      out.write("\t  text-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ribbon span {\r\n");
      out.write("\t  font-size: 10px;\r\n");
      out.write("\t  font-weight: bold;\r\n");
      out.write("\t  color: #FFF;\r\n");
      out.write("\t  text-transform: uppercase;\r\n");
      out.write("\t  text-align: center;\r\n");
      out.write("\t  line-height: 20px;\r\n");
      out.write("\t  transform: rotate(-45deg);\r\n");
      out.write("\t  -webkit-transform: rotate(-45deg);\r\n");
      out.write("\t  width: 100px;\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t  background: #79A70A;\r\n");
      out.write("\t  background: linear-gradient(#F70505 0%, #8F0808 100%);\r\n");
      out.write("\t  box-shadow: 0 3px 10px -5px rgba(0, 0, 0, 1);\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 19px; left: -21px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ribbon span::before {\r\n");
      out.write("\t  content: \"\";\r\n");
      out.write("\t  position: absolute; left: 0px; top: 100%;\r\n");
      out.write("\t  z-index: -1;\r\n");
      out.write("\t  border-left: 3px solid #8F0808;\r\n");
      out.write("\t  border-right: 3px solid transparent;\r\n");
      out.write("\t  border-bottom: 3px solid transparent;\r\n");
      out.write("\t  border-top: 3px solid #8F0808;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ribbon span::after {\r\n");
      out.write("\t  content: \"\";\r\n");
      out.write("\t  position: absolute; right: 0px; top: 100%;\r\n");
      out.write("\t  z-index: -1;\r\n");
      out.write("\t  border-left: 3px solid transparent;\r\n");
      out.write("\t  border-right: 3px solid #8F0808;\r\n");
      out.write("\t  border-bottom: 3px solid transparent;\r\n");
      out.write("\t  border-top: 3px solid #8F0808;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.images{\r\n");
      out.write("\t\twidth:50px;\r\n");
      out.write("\t\theight:60px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		response.setHeader("Cache-Control","no-cache, no-store, must-revalidate");
		System.out.println((User)session.getAttribute("user"));
		//Session check
		if((User)session.getAttribute("user")==null)
		{
			System.out.println("Hi");
			response.sendRedirect("index.html");
			return;
		}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li class=\"logout\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">Logout</a></li>\r\n");
      out.write("\t\t<li class=\"nameDisp\">Hi, ");
      out.print(((User)(session.getAttribute("user"))).getName());
      out.write("</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<!-- Now fetch the data -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t");

		
		DAO dao=(DAO)session.getAttribute("dao");
		ResultSet rs=dao.getItems((User)session.getAttribute("user"));
		do
		{
		System.out.println(rs);
      out.write("\r\n");
      out.write("\t\t\t<div class=\"cards\">\r\n");
      out.write("\t\t\t\t");
if(rs.getString("itemtype").equals("newarr")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"ribbon\"><span>NEW</span></div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<img src='<c:url value=\"");
      out.print("images/"+rs.getString("name")+".png" );
      out.write("\"></c:url>' class=\"images\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t\t<h3>");
      out.print(rs.getString("name"));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(rs.getString("itemtype").equals("discount"))
					{
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"origPrice\">\r\n");
      out.write("\t\t\t\t\t\tPrice: Rs. ");
      out.print(rs.getString("price"));
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"price\">\r\n");
      out.write("\t\t\t\t\tPrice: Rs. \r\n");
      out.write("\t\t\t\t\t");

					int disc=Integer.parseInt(rs.getString("discount"));
					int orig=Integer.parseInt(rs.getString("price"));
					int newprice=orig-(int)(orig*disc/100.0);
					out.print(newprice);
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t");
}
		while(rs.next());
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
